<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MpyjVPN.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MpyjVPN.Domain\MpyjVPN.Domain.csproj" />
    <ProjectReference Include="..\MpyjVPN.Infrastructure\MpyjVPN.Infrastructure.csproj" />
  </ItemGroup>
</Project>
